<a href="https://colab.research.google.com/github/aisyahaini/data-mining/blob/main/PreprocessingDataLensa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aisyah Nuraini
A11.2022.14161
A11.43UG1
Data Mining

In [ ]:
#untuk menampilkan packages yang telah ter-install di lingkungan python
pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.6
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.1.0
blinker                          1.4
bl

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python untuk komputasi matriks Matplotlib merupakan library python untuk presentasi data berupa grafik/plot Pandas untuk mengimport data dari luar seperti csv

In [ ]:
dataset = pd.read_csv('missing_lens.csv')

x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(x)

[['young' nan 'no' 'reduced']
 ['young' 'myope' 'no' 'normal']
 ['young' 'myope' 'yes' nan]
 ['young' 'myope' 'yes' 'normal']
 ['young' 'hypermetrope' 'no' 'reduced']
 ['young' nan 'no' 'normal']
 ['young' 'hypermetrope' 'yes' 'reduced']
 ['young' 'hypermetrope' nan 'normal']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'no' nan]
 ['pre-presbyopic' 'myope' 'yes' 'reduced']
 ['pre-presbyopic' nan 'yes' 'normal']
 ['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['pre-presbyopic' 'hypermetrope' 'no' nan]
 ['pre-presbyopic' 'hypermetrope' 'yes' 'reduced']
 ['pre-presbyopic' nan 'yes' 'normal']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'myope' 'no' nan]
 ['presbyopic' 'myope' nan 'reduced']
 ['presbyopic' 'myope' 'yes' 'normal']
 ['presbyopic' nan 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'no' nan]
 ['presbyopic' 'hypermetrope' nan 'reduced']
 ['presbyopic' 'hypermetrope' 'yes' 'normal']]


In [ ]:
print(y)

['none' 'soft' 'none' 'hard' 'none' 'soft' 'none' 'hard' 'none' 'soft'
 'none' 'hard' 'none' 'soft' 'none' 'none' 'none' 'none' 'none' 'hard'
 'none' 'soft' 'none' 'none']


In [ ]:
#train_test_split didalamnya ada x sebagai dataset fitur, y sebagai dataset target
#dibagi menjadi 2 yaitu data pelatihan (x_train dan y_train) dan data pengujian (x_test, y_test)
from sklearn.model_selection import train_test_split

#test_size untuk proporsi data yang dikirim ke data pengujian
#random_state untuk mengontrol keacakan
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
print(x_train)

[['young' 'myope' 'no' 'normal']
 ['pre-presbyopic' 'hypermetrope' 'no' nan]
 ['presbyopic' 'hypermetrope' 'yes' 'normal']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['young' 'hypermetrope' 'yes' 'reduced']
 ['presbyopic' 'myope' 'no' nan]
 ['young' 'hypermetrope' 'no' 'reduced']
 ['young' 'myope' 'yes' nan]
 ['young' nan 'no' 'normal']
 ['presbyopic' 'myope' nan 'reduced']
 ['pre-presbyopic' 'myope' 'no' nan]
 ['young' 'hypermetrope' nan 'normal']
 ['presbyopic' 'myope' 'yes' 'normal']
 ['young' 'myope' 'yes' 'normal']
 ['young' nan 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'no' nan]
 ['pre-presbyopic' nan 'yes' 'normal']
 ['pre-presbyopic' 'hypermetrope' 'no' 'reduced']]


In [ ]:
print(x_test)

[['pre-presbyopic' nan 'yes' 'normal']
 ['pre-presbyopic' 'myope' 'yes' 'reduced']
 ['presbyopic' 'hypermetrope' nan 'reduced']
 ['pre-presbyopic' 'hypermetrope' 'yes' 'reduced']
 ['presbyopic' nan 'no' 'reduced']]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [ ]:
print(x)

[['young' 'myope' 'no' 'reduced']
 ['young' 'myope' 'no' 'normal']
 ['young' 'myope' 'yes' 'reduced']
 ['young' 'myope' 'yes' 'normal']
 ['young' 'hypermetrope' 'no' 'reduced']
 ['young' 'myope' 'no' 'normal']
 ['young' 'hypermetrope' 'yes' 'reduced']
 ['young' 'hypermetrope' 'no' 'normal']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'normal']
 ['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['pre-presbyopic' 'hypermetrope' 'yes' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'normal']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'myope' 'yes' 'normal']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'yes' 'normal']]


In [ ]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', 'passthrough', [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[['young' 'myope' 'no' 'reduced']
 ['young' 'myope' 'no' 'normal']
 ['young' 'myope' 'yes' 'reduced']
 ['young' 'myope' 'yes' 'normal']
 ['young' 'hypermetrope' 'no' 'reduced']
 ['young' 'myope' 'no' 'normal']
 ['young' 'hypermetrope' 'yes' 'reduced']
 ['young' 'hypermetrope' 'no' 'normal']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'normal']
 ['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['pre-presbyopic' 'hypermetrope' 'yes' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'normal']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'myope' 'yes' 'normal']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'no' 'reduced']
 ['presbyopic' 'hypermetrope' 'yes' 'normal']]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 2 1 0 1 2 1 0 1 2 1 0 1 2 1 1 1 1 1 0 1 2 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[['presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'reduced']
 ['young' 'hypermetrope' 'no' 'reduced']
 ['young' 'myope' 'yes' 'reduced']
 ['presbyopic' 'myope' 'yes' 'normal']
 ['young' 'hypermetrope' 'yes' 'reduced']
 ['young' 'hypermetrope' 'no' 'normal']
 ['presbyopic' 'hypermetrope' 'no' 'reduced']
 ['young' 'myope' 'no' 'normal']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['young' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'normal']
 ['presbyopic' 'hypermetrope' 'yes' 'normal']
 ['presbyopic' 'hypermetrope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'no' 'reduced']
 ['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['pre-presbyopic' 'myope' 'yes' 'normal']
 ['young' 'myope' 'no' 'normal']]


In [ ]:
print(x_test)

[['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['young' 'myope' 'yes' 'normal']
 ['pre-presbyopic' 'hypermetrope' 'yes' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']]


In [ ]:
print(y_train)

[1 1 1 1 0 1 0 2 2 1 1 1 1 1 2 1 1 0 2]


In [ ]:
print(y_test)

[2 1 0 1 1]


Data training nantinya akan digunakan untuk melatih algoritma dalam mencari model yang sesuai, sedangkan data testing akan dipakai untuk menguji dan mengetahui performa model yang didapatkan pada tahapan testing.


In [ ]:
# Jika x_train sebelumnya memiliki kurang dari 4 kolom, tidak ada fitur yang tersisa setelah slicing ini
x_train = x_train[:, 4:]

In [ ]:
#x_train.shape untuk menampilkan bentuk dari suatu variabel atau array
print(x_train.shape)

(19, 0)


In [ ]:
print(x_test)

[['pre-presbyopic' 'hypermetrope' 'no' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']
 ['young' 'myope' 'yes' 'normal']
 ['pre-presbyopic' 'hypermetrope' 'yes' 'reduced']
 ['presbyopic' 'myope' 'no' 'reduced']]
